name: Create EC2 Instance

on:
  workflow_dispatch:

jobs:
  create-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0e86e20dae9224db8 \
            --instance-type t2.micro \
            --key-name mybackend \
            --security-group-ids sg-027701b86ea260afe \
            --subnet-id subnet-06e15f3bec55eb8ce \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=My-First-Ubuntu-EC2}]" \
            --count 1
